#+TITLE: Entities
#+AUTHOR: VLEAD
#+DATE: [2016-06-07 Tue]
#+SETUPFILE: ../../org-templates/level-2.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction

In the object implementation of the Outreach Portal, 
all entities are Objects.  In addition, there is an object 
called =System= that holds the state of the application 
(=user-set=, =session-set=, etc.).

Each of the entities of the data model is implemented as
an object.  Each entity is defined via a class definition, a
constructor and getter and setter methods that access and
mutate the fields of the entity. 

The main idea in the object model is that certain relations
of the data model (those that are total functions) are
implemented as /fields/.  For example the =User= object has
a field called =email= that holds an object of type =Email=.

As a start, we do not implement all relations of the data
model.  For example, the relation =user: Email > User?= is
not implemented.  It should be, if we desire to have an
implementation that is /complete/ with respect to the data
model.  Which elements of the data model are implemented and
which are not are decisions based on the end user
requirements of the application.


* Name

=Name= is a value class with type =is_alphabetic_str=.

#+NAME: class_Name
#+begin_src python
Name = ClassTemplate.mk_class("Name", name=is_alphabetic_str)
is_name = is_inst(Name)
check_name = check_pred(is_name)

#+end_src

*** Test Name
#+NAME: class_TestName
#+BEGIN_SRC python
class TestName(TestCase):
    TESTING = True

    def test_instantiate_name(self):
        print "test_instantiate_name"
        self.assertEqual(is_name(Name(name="Jimi Hendrix")), True)
        self.assertEqual(Name(name="Jimi Hendrix").get("name"), "Jimi Hendrix")
        self.assertRaises(TypeError, Name, name="Jimi 123 Hendrix")

#+END_SRC


* Email
=Name= is a value class with type =is_email_str=.
#+NAME: class_Email
#+begin_src python
Email = ClassTemplate.mk_class("Email", email=is_email_str)

Email.__eq__ = lambda self, other: \
                  isinstance(other, self.__class__) and \
                  self.get("email") == other.get("email")

is_email = is_inst(Email)
check_email = check_pred(is_email)

#+end_src

** Test Email
#+NAME: class_testEmail
#+BEGIN_SRC python
class TestEmail(TestCase):
    TESTING = True

    def test_instantiate_email(self):
        print "test_instantiate_email"
        self.assertEqual(is_email(Email(email="jimi@gnu.org")), True)
        self.assertEqual(Email(email="jimi@gnu.org").get("email"),
                         "jimi@gnu.org")
        self.assertRaises(TypeError, Name, name="jimi@@gnu.org")


    def test_equality_of_email(self):
        print "test_equality_of_email"
        em1 = Email(email="jimi@gnu.org")
        self.assertEqual(em1 == em1, True)

        em2 = Email(email="didley@gnu.org")
        self.assertEqual(em1 == em2, False)

#+END_SRC


* OC
  A =OC= entity has fields =name= of type =Name=,
 institute of type =Institute=.
#+NAME: class_OC
#+BEGIN_SRC python

OC= ClassTemplate.mk_class("OC",institute=is_institute)

OC.__eq__ = lambda self,other: \
            isinstance(other, self.__class__) and \
            self.get("institute") == other.get("institute")


is_oc = is_inst(OC)
check_oc = check_pred(is_oc)

OC.spokes = []

def set_spokes(self, centre):
    if is_nc(centre):
        self.spokes.append(centre)


OC.setspokes = set_spokes
def get_spokes(self):
    return self.spokes
OC.getspokes= get_spokes
OC.__eq__ = lambda self,other: \
            isinstance(other, self.__class__) and \
            self.get("institute") == other.get("institute")


is_oc = is_inst(OC)
check_oc = check_pred(is_oc)


#+END_SRC

** Test OC

#+NAME: class_TestOC
#+BEGIN_SRC python
class TestOC(TestCase):
    TESTING = True

    def test_instatiate_OC(self):
        print "test_instantiate_user"
        oc = OC(institute=Institute(name="IIITH",address="Hyderabad"))        
                  
        self.assertEqual(is_oc(oc), True)
#+END_SRC

#+NAME: class_TestOC
#+BEGIN_SRC python
class TestOC(TestCase):
    TESTING = True

    def test_instatiate_OC(self):
        print "test_instantiate_user"
        oc = OC(institute=Institute(name="IIITH",address="Hyderabad"))        
                  
        self.assertEqual(is_oc(oc), True)

    
    def test_sets_spokes_on_OC(self):
        print "test_sets_spokes_on_oc"
        oc = OC(institute=Institute(name="IIITH",address="Hyderabad"))       

        nc = NC(institute=Institute(name="HCU",address="Hyderabad"), hub=oc)       
        self.assertEqual((nc.get("institute")).get("name"), "HCU")
    
        oc.setspokes(nc)
        
        self.assertEqual(oc.getspokes()[0].get("institute").get("name"), "HCU")    
#+END_SRC


* NC
  A =NC= entity has fields =name= of type =Name=,
 institute of type =Institute=.
#+NAME: class_NC
#+BEGIN_SRC python

NC= ClassTemplate.mk_class("NC", institute=is_institute, hub=is_oc)

is_nc = is_inst(NC)
check_nc = check_pred(is_nc)

#+END_SRC

** Test NC

#+NAME: class_TestOC
#+BEGIN_SRC python
class TestNC(TestCase):
    TESTING = True

    def test_instatiate_NC(self):
        print "test_instantiate_user"
        nc = NC(institute=Institute(name="HCU",address="Hyderabad"), hub=OC(institute=Institute(name="IIITH", address="Hyderabad")))        
                  
        self.assertEqual(is_nc(nc), True)
#+END_SRC


* Role
   =Role= is an entity that has a field =name= which is an alphabetic string

#+NAME: class_Role
#+BEGIN_SRC python
def is_centre(value):
    if value == None or is_oc(value) or is_nc(value):
        return True
    else:
        raise False
   
Role = ClassTemplate.mk_class("Role", 
                              name=is_alphabetic_str,
                              centre=is_centre)

is_role = is_inst(Role)
check_role = check_pred(is_role)
Role.admin = Role(name="admin",centre=None)
Role.reviewer = Role(name="reviewer",centre=None)
Role.guest = Role(name="guest",centre=None)
Role.is_admin = lambda role: role.name == 'admin'
Role.is_reviewer = lambda role: role.name == 'reviewer'
Role.is_guest = lambda role: role.guest == 'guest'


#+END_SRC

** Test Role
#+NAME: class_TestRole
#+BEGIN_SRC python
class TestRole(TestCase):
    TESTING = True

    def test_instantiate_role(self):
        print "test_instantiate_role"
        self.assertEqual(is_role(Role(name="admin", centre=None)), True)
        a_role = Role(name="admin", centre=None)
        self.assertEqual(check_role(a_role), a_role)
        self.assertEqual(Role(name="admin", centre=None).get("name"), "admin")
        self.assertRaises(TypeError, Role, name="admin123", centre=None)

    def test_sets_on_role(self):
        print "test_sets_on_role"
        u_role = Role(name="guest", centre=None)
        self.assertEqual(u_role.get("name"), "guest")
        u_role.set(name="admin")
        self.assertEqual(u_role.get("name"), "admin")

    def test_set_and_get_centre(self):
        print "test_set_and_get_centre"
        oc = OC(institute=Institute(name="IIITH", address="Hyderabad"))
        occ_role = Role(name="OCC", centre=oc)
        self.assertEqual(occ_role.get("name"), "OCC")
        self.assertEqual(occ_role.get("centre"), oc)

#+END_SRC


* User
  A =User= entity has fields =name= of type =Name=, =email= of type =Email= and
  role of type =Role=.

#+NAME: class_User
#+BEGIN_SRC python
User = ClassTemplate.mk_class("User", 
                              name=is_name, 
                              email=is_email
                              )
User.roles = []
def set_role(self, role):
    if is_role(role):
       self.roles.append(role)

User.set_role = set_role

def get_role(self):
    return self.roles

User.get_role = get_role

User.__eq__ = lambda self, other: \
                  isinstance(other, self.__class__) and \
                  self.get("email") == other.get("email")

is_user = is_inst(User)
check_user = check_pred(is_user)

#+END_SRC

** Test User
#+NAME: class_TestUser
#+BEGIN_SRC python
class TestUser(TestCase):
    TESTING = True

    def test_instantiate_user(self):
        print "test_instantiate_user"
        user = User(name=Name(name="Jimi Hendrix"),
                    email=Email(email="jimi@gnu.org"))
        self.assertEqual(is_user(user), True)

    def test_sets_on_user(self):
        print "test_sets_on_user"
        user = User(name=Name(name="Jimi Hendrix"),
                    email=Email(email="jimi@gnu.org")
                   )

        user.set_role(role=Role(name="user",centre=None))

        self.assertEqual(user.get("name").get("name"), "Jimi Hendrix")
        self.assertEqual(user.get("email").get("email"), "jimi@gnu.org")
        self.assertEqual(user.get_role()[0].get("name"), "user")

        
    def test_equality_on_user(self):
        print "test_equality_on_user"
        user1 = User(name=Name(name="Jimi Hendrix"),
                     email=Email(email="jimi@gnu.org")
                    )
        self.assertEqual(user1 == user1, True)

#+END_SRC


* Institute

=Institute= is an entity that has two fields =name= which is an alphabetic
string and =address= which is a string

#+NAME: class_Institute
#+BEGIN_SRC python

Institute = ClassTemplate.mk_class("Institute", name=is_alphabetic_str, address=is_str)
is_institute = is_inst(Institute)
check_institute = check_pred(is_institute)

#+END_SRC

** Test Institute
#+NAME: class_TestInstitute
#+BEGIN_SRC python
class TestInstitute(TestCase):
    TESTING = True

    def test_instantiate_institute(self):
        print "test_instantiate_institute"
        self.assertEqual(is_institute(Institute(name="IIIT",address="Hyderabad")), True)
        institute_ex = Institute(name="IIIT",address="Hyderabad")
        self.assertEqual(check_institute(institute_ex), institute_ex)
        self.assertEqual(check_institute(institute_ex).get("name"), "IIIT")
        self.assertRaises(TypeError, Institute, name="IIIT123")
#+END_SRC
  

* Session
    A session stores the user information.  The session object defines the set
    of operations allowed by the system.  

#+NAME: class_Session
#+BEGIN_SRC python
Session = ClassTemplate.mk_class("Session", user=is_user, role=is_role)

is_session = is_inst(Session)
check_session = check_pred(is_session)

#+END_SRC

** Test Session

   Test cases to test Seesion entity

#+NAME: class_TestSession
#+BEGIN_SRC python
class TestSession(TestCase):
    TESTING = True

    def test_instantiate_session(self):
        print "test_instantiate_user"
        user = User(name=Name(name="Jimi Hendrix"),
                    email=Email(email="jimi@gnu.org")
                   )
        role = Role(name=("admin"), centre=None)
        session = Session(user=user, role=role)
        self.assertEqual(is_session(session), True)

    def test_sets_on_session(self):
        print "test_sets_on_session"
        user = User(name=Name(name="Jimi Hendrix"),
                    email=Email(email="jimi@gnu.org")
                   )
        role = Role(name=("admin"), centre=None)
        session = Session(user=user, role=role)

        user = User(name=Name(name="Bo Didley"),
                    email=Email(email="didley@gnu.org")
                   )

        session.set(user=user)
        self.assertEqual(session.get("user").get("email").get("email"),
                         "didley@gnu.org")

#+END_SRC




* Infra                                                         :boilerplate:

** sources
*** Imports 
#+name: imports_for_sources
#+BEGIN_SRC python
# -*- coding: utf-8 -*-
from runtime.utils.type_utils import *
from runtime.utils.class_templates import *
from runtime.exceptions.exceptions import *
#+end_src


** Tests
*** Imports 
#+name: imports_for_tests
#+BEGIN_SRC python
# -*- coding: utf-8 -*-
import unittest
from unittest import TestCase
from runtime.utils.type_utils import *
from runtime.utils.class_templates import *
from entities import *
#+end_src

*** Running tests
#+NAME: run_test_cases
#+BEGIN_SRC python
if __name__ == '__main__':
    unittest.main()

#+END_SRC


* Tangling                                                      :boilerplate:

** sources
#+BEGIN_SRC python :tangle entities.py :eval no :noweb yes
<<imports_for_sources>>
<<class_Name>>
<<class_Email>>
<<class_Institute>>
<<class_OC>>
<<class_NC>>
<<class_Role>>
<<class_User>>
<<class_Session>>
#+end_src


** tests
#+BEGIN_SRC python :tangle test_entities.py :eval no :noweb yes
<<imports_for_tests>>
<<class_TestName>>
<<class_TestEmail>>
<<class_TestRole>>
<<class_TestUser>>
<<class_TestInstitute>>
<<class_TestOC>>
<<class_TestNC>>
<<class_TestSession>>
<<run_test_cases>>
#+end_src
