#+TITLE: Requirements for Outreach Portal 3.0
#+AUTHOR: VLEAD
#+DATE: [2016-06-15 Wed]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ../org-templates/level-1.org
#+options: ^:nil
#+LATEX: Literal LaTeX code for export

Requirements of a Portal whose objective is to help advance the outreach of
Virtual Labs are captured here. 

* User

  User is an entity in the system.  There are several user(s) in the system
  whose type is =User=.  The interaction of a user with the system is defined
  by the requirements below.

** Req 1
   The system has users.
** Req 2
   Each user has an email address (string that corresponds to a
   valid email addr).  
** Req 3
   Email identifies a user.  Two users with the same email
   are the same users. 
** Req 4
   Each user has a Name (string).
** Req 5
   Each user has atleast one role, and by default when a user is created, the
   role that is associated with the newly created user is guest.

   
* Role
** Req 1 
   There are 6 kinds of roles: =admin=, =guest=, =reviewer=, =noc= =occ(oc)=,
   =ncc(nc)=.  Each role determines what data access privileges are available
   to the user.

   =noc= - National Outreach Coordinator
   =oc= - Outreach Center
   =occ= - Outreach Center Coordinator
   =nc= - Nodal Center
   =ncc= - Nodal Center Coordinator

** Req 2
   Each user is mapped to at least one role meaning a user can have one or more
   roles.  In any given session, a user is mapped to a single role.

** Req 3
   1. A user with role admin has the ability to:

      1. Create a new user, Read and Update information of all users, and
         Delete all other users.

   2. A user with role guest has the ability to:

      1. View certain information of the Outreach Portal. (to be defined)
      
   3. A user with role =reviewer= has the ability to:

      1. View all the information of the Outreach Portal.

   4. A user with role =noc= has the ability to:

      1. Create Outreach Centers (=oc= s)

      2. Create users

      3. Assign role occ(oc) to users

      4. Set targets to Outreach Centers

   5. A user with the role =occ(oc)= has the ability to:

      1. Manage the outreach center =oc=.

      2. Create, Read, Update and delete nodal centers.

      3. Create users

      4. Assign role =ncc(nc)= to users where =nc= is nodal center belonging to
         the outreach center =oc=.

   6. A user with the role =ncc(nc)= has the ability to:

      1. Manage the nodal center =nc=.


* Outreach Center
  
** Req 1
   An outreach center (=OC=) is hosted in an institute. 
** Req 2
   The target usage for an =OC= is set by user while donning the role =admin=
** Req 3
   =OC= monitors and coordinates outreach activity for a region.  This is
   achieved by creating one or more nodal centers that are associated with an
   =OC= to carry out outreach activity to meet the targets for an =OC=.
** Req 4
   Each =OC= has zero or more coordinators associated with it.
** Req 5
   =OCC= of an =OC= reviews activities of all the nodal centers associated with
   it and upon review, either approves or rejects the activities.
** Req 6
   An =OC= is created by user while donning the role =admin=


* Nodal Center
** Req 1
   An nodal center (=NC=) is hosted in an institute.
** Req 2
   Each =NC= is associated with a unique outreach center.
** Req 3
   The target for a =NC= is set by the Outreach Center Coordinator (=OCC=) of
   the =OC= with which this =NC= is associated with.
** Req 4
   Each =NC= has zero or more users whose role is ncc(nc)  associated with it.
** Req 5
   A Nodal Center Coordinator (=NCC=) conducts activities to meet the target of
   =NC=.
** Req 6
   A =NCC= submits all the artifacts associated with an activity for approval
   by an =OCC=.


* Activities
** Req 1
   A Workshop is an activity and a workshop is conducted at an Institute.
** Req 3
   A workshop has participants - students and a nodal center coordinator. 
** Req 3
   Each workshop has a target and actual usage of Virtual Labs measured in
   terms of experiments performed by the participants. 
** Req 4
   There are different types of artifacts associated with each workshop -
   attendance sheet, photos, feedback and report. 


* Institute
** Req 1
   The system has institutes.
** Req 2
   Each outreach center is associated to exactly one institute

** Req 3
   Each nodal center is associated to exactly one institute
** Req 4
   The hosting institute of an outreach center and a nodal center can be the
   same.
** Req 5
   A workshop is conducted at an institute


* Sessions
** Req 1
   Users are required to login into the system.

** Req 2
   Each user once logged in is associated with a session.

** Req 3
   Operations are permitted only if the user is logged in into the system.

** Req 4
   Users can have more than one session at a given time but no two sessions of
   a user can have the same role.


* COMMENT Views
** Admin
   

* Questions/scenarios
  1. What is the information that a user when logged in with role =guest= is
     presented with?
     
     The information could be related to the total usage, upcoming workshops
     etc.

  2. When a user is logged in with role =reviewer=, most of the information
     available with the portal should be presented.  The information is targets
     and actual usage, outreach centers, nodal centers, workshops conducted,
     workshops planned. 



